repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/4Catalyzer/fourmat
    rev: v0.11.1
    hooks:
      - id: fourmat
