repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.1.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/4Catalyzer/fourmat
    rev: v0.4.3
    hooks:
      - id: fourmat
