repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/4Catalyzer/fourmat
    rev: v1.0.0
    hooks:
      - id: fourmat
        additional_dependencies: ['setuptools>=74']
