sudo: false

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"

env:
  - TOXENV=py-s3

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py-base
    - python: "3.6"
      env: TOXENV=py-base
    - # TODO: Remove this workaround once travis-ci/travis-ci#9815 is fixed.
      sudo: true
      dist: xenial
      python: "3.7"
      env: TOXENV=py-s3

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install -U pip
install:
  - pip install -U codecov tox

script:
  - python setup.py test

after_success:
  - codecov

branches:
  only:
    - master
