dist: xenial

language: python
python:
  - "3.7"
  - "3.6"

env:
  - TOXENV=py-s3

matrix:
  include:
    - env: TOXENV=lint
    - env: TOXENV=py-base
    - python: pypy3

cache: pip

before_install:
  - pip install -U pip
install:
  - pip install -U codecov tox

script:
  - python setup.py test

after_success:
  - codecov

branches:
  only:
    - master
