language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "pypy"

env:
  - TOXENV=py-s3

matrix:
  include:
    - python: "3.7"
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=py-base
    - python: "3.7"
      env: TOXENV=py-s3

cache: pip

before_install:
  - pip install -U pip
install:
  - pip install -U codecov tox

script:
  - python setup.py test

after_success:
  - codecov

branches:
  only:
    - master
